version: '3.1'

services:
  web:
    build: .
    ports:
      - "8000:5173"
    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /code

  mongoAparts:
    image: mongo:8.0-noble
    container_name: apart-mongodb
    volumes:
      - "./db:/data/db"
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root1337
      MONGO_INITDB_ROOT_PASSWORD: example1337